// Lesen content (§14.2). Data only — no logic, no DOM.
//
// Canonical item order for the box digit string (§9.2): packs in this array's
// order, items in theirs. NEVER reorder or delete an entry — append only, or
// every child's Leitner boxes shift under her.
//
// Authoring rules (enforced by tests/lesen-content.test.js):
//  - every word has ONE unambiguous, mainstream emoji; inside a pack, words
//    and emoji are unique, and no two emoji are near-twins (🐶 vs 🐺 is fine,
//    🐶 vs 🐕 is a bug) — distractors are drawn from the same pack (§14.3);
//  - a Schwer item is a reading passage `{ text, q, a }`: `text` is a short
//    passage (~3 lines, ≤ 175 chars, sentences ending "."), `q` a question
//    ending "?", and `a` FOUR distinct answers with the CORRECT one FIRST
//    (optionsFor shuffles them). The three wrong answers are plausible but
//    clearly wrong to someone who READ the passage — the point is comprehension,
//    not a guess (§14.2).
//
// German only for now; an English set is a later milestone (§14.6) and slots
// in as a second key beside `de`.
export const CONTENT = {
  de: {
    packs: [
      // --- Leicht: short frequent words, 1–2 syllables, 10 each ---
      { key: "tiere", diff: 0, items: [
        { w: "Hund", e: "🐶" },
        { w: "Katze", e: "🐱" },
        { w: "Maus", e: "🐭" },
        { w: "Fisch", e: "🐟" },
        { w: "Vogel", e: "🐦" },
        { w: "Pferd", e: "🐴" },
        { w: "Kuh", e: "🐮" },
        { w: "Schwein", e: "🐷" },
        { w: "Frosch", e: "🐸" },
        { w: "Ente", e: "🦆" },
      ] },
      { key: "essen", diff: 0, items: [
        { w: "Brot", e: "🍞" },
        { w: "Apfel", e: "🍎" },
        { w: "Eis", e: "🍦" },
        { w: "Käse", e: "🧀" },
        { w: "Pizza", e: "🍕" },
        { w: "Banane", e: "🍌" },
        { w: "Ei", e: "🥚" },
        { w: "Milch", e: "🥛" },
        { w: "Keks", e: "🍪" },
        { w: "Honig", e: "🍯" },
      ] },
      { key: "zuhause", diff: 0, items: [
        { w: "Bett", e: "🛏️" },
        { w: "Buch", e: "📖" },
        { w: "Tür", e: "🚪" },
        { w: "Uhr", e: "🕐" },
        { w: "Lampe", e: "💡" },
        { w: "Schere", e: "✂️" },
        { w: "Stuhl", e: "🪑" },
        { w: "Seife", e: "🧼" },
        { w: "Besen", e: "🧹" },
        { w: "Schlüssel", e: "🔑" },
      ] },
      { key: "natur", diff: 0, items: [
        { w: "Baum", e: "🌳" },
        { w: "Sonne", e: "☀️" },
        { w: "Mond", e: "🌙" },
        { w: "Stern", e: "🌟" },
        { w: "Blume", e: "🌸" },
        { w: "Wolke", e: "☁️" },
        { w: "Feuer", e: "🔥" },
        { w: "Berg", e: "⛰️" },
        { w: "Pilz", e: "🍄" },
        { w: "Blatt", e: "🍁" },
      ] },
      // --- Mittel: compounds & consonant clusters, 10 each ---
      { key: "tierwelt", diff: 1, items: [
        { w: "Schmetterling", e: "🦋" },
        { w: "Eichhörnchen", e: "🐿️" },
        { w: "Schildkröte", e: "🐢" },
        { w: "Elefant", e: "🐘" },
        { w: "Pinguin", e: "🐧" },
        { w: "Krokodil", e: "🐊" },
        { w: "Marienkäfer", e: "🐞" },
        { w: "Papagei", e: "🦜" },
        { w: "Delfin", e: "🐬" },
        { w: "Känguru", e: "🦘" },
      ] },
      { key: "unterwegs", diff: 1, items: [
        { w: "Fahrrad", e: "🚲" },
        { w: "Feuerwehrauto", e: "🚒" },
        { w: "Flugzeug", e: "✈️" },
        { w: "Straßenbahn", e: "🚋" },
        { w: "Hubschrauber", e: "🚁" },
        { w: "Traktor", e: "🚜" },
        { w: "Rakete", e: "🚀" },
        { w: "Polizeiauto", e: "🚓" },
        { w: "Segelboot", e: "⛵" },
        { w: "Krankenwagen", e: "🚑" },
      ] },
      { key: "kueche", diff: 1, items: [
        { w: "Schokolade", e: "🍫" },
        { w: "Erdbeere", e: "🍓" },
        { w: "Spiegelei", e: "🍳" },
        { w: "Geburtstagskuchen", e: "🎂" },
        { w: "Wassermelone", e: "🍉" },
        { w: "Brezel", e: "🥨" },
        { w: "Pfannkuchen", e: "🥞" },
        { w: "Kartoffel", e: "🥔" },
        { w: "Zitrone", e: "🍋" },
        { w: "Karotte", e: "🥕" },
      ] },
      { key: "draussen", diff: 1, items: [
        { w: "Regenbogen", e: "🌈" },
        { w: "Gewitter", e: "⛈️" },
        { w: "Schneemann", e: "⛄" },
        { w: "Schneeflocke", e: "❄️" },
        { w: "Drachen", e: "🪁" },
        { w: "Zelt", e: "⛺" },
        { w: "Fußball", e: "⚽" },
        { w: "Luftballon", e: "🎈" },
        { w: "Sonnenblume", e: "🌻" },
        { w: "Regenschirm", e: "☔" },
      ] },
      // --- Schwer: reading passages, comprehension question, 4 answers (§14.2).
      // `text` is a short passage (~3 lines), `q` the question, and `a` the four
      // options with the CORRECT one FIRST (optionsFor shuffles them). Rewritten
      // in place from the old Quatsch pairs: the item positions are unchanged, so
      // no child's Leitner box shifts (§9.2). The skill is comprehension now — a
      // 50/50 verdict rewarded guessing; four answers over a passage do not. ---
      { key: "leseTiere", diff: 2, items: [
        { text: "Der Igel läuft nachts durch den Garten. Er sucht Käfer und Würmer zum Fressen. Am Tag schläft er unter den Blättern.",
          q: "Wann sucht der Igel sein Futter?", a: ["In der Nacht.", "Am Morgen.", "Am Mittag.", "Am Nachmittag."] },
        { text: "Die Schwalbe baut ihr Nest aus Lehm. Sie klebt es oben an die Hauswand. Dort sind die Küken sicher vor der Katze.",
          q: "Woraus baut die Schwalbe ihr Nest?", a: ["Aus Lehm.", "Aus Stroh.", "Aus Federn.", "Aus Papier."] },
        { text: "Der Biber fällt Bäume mit seinen Zähnen. Aus den Ästen baut er einen Damm im Fluss. So staut sich das Wasser zu einem Teich.",
          q: "Womit fällt der Biber die Bäume?", a: ["Mit seinen Zähnen.", "Mit einer Säge.", "Mit den Pfoten.", "Mit dem Schwanz."] },
        { text: "Im Herbst sammelt das Eichhörnchen Nüsse. Es vergräbt sie überall im Wald. Im Winter findet es nicht alle wieder.",
          q: "Warum findet es im Winter nicht alle Nüsse?", a: ["Es hat sie überall vergraben.", "Es hat keinen Hunger.", "Der Bär hat sie gefressen.", "Es schläft den ganzen Winter."] },
        { text: "Die Fledermaus schläft am Tag kopfüber in der Höhle. Erst wenn es dunkel wird, fliegt sie los. In der Nacht jagt sie Mücken.",
          q: "Wie schläft die Fledermaus?", a: ["Kopfüber.", "Im Nest.", "Auf dem Rücken.", "Im Wasser."] },
        { text: "Der junge Storch übt das Fliegen auf dem Dach. Im Sommer ist er noch zu klein für die Reise. Im Herbst fliegt er in den warmen Süden.",
          q: "Wann fliegt der Storch in den Süden?", a: ["Im Herbst.", "Im Sommer.", "Im Winter.", "Im Frühling."] },
        { text: "Die Biene fliegt von Blüte zu Blüte. Sie sammelt süßen Nektar in ihrem Bauch. Im Bienenstock machen die Bienen daraus Honig.",
          q: "Was machen die Bienen aus dem Nektar?", a: ["Honig.", "Wachs.", "Marmelade.", "Zucker."] },
        { text: "Der Delfin lebt im Meer, ist aber kein Fisch. Er muss zum Atmen an die Oberfläche kommen. Durch ein Loch am Kopf holt er Luft.",
          q: "Warum kommt der Delfin an die Oberfläche?", a: ["Um Luft zu holen.", "Um zu schlafen.", "Um Fische zu fangen.", "Um sich zu sonnen."] },
        { text: "Der Maulwurf lebt tief unter der Erde. Mit den breiten Pfoten gräbt er lange Gänge. Draußen sieht man nur die kleinen Erdhügel.",
          q: "Was sieht man vom Maulwurf draußen?", a: ["Kleine Erdhügel.", "Seine Pfoten.", "Sein Nest.", "Seine Augen."] },
        { text: "Die Schnecke trägt ihr Haus auf dem Rücken. Bei Gefahr zieht sie sich ganz hinein. Langsam kriecht sie über das feuchte Blatt.",
          q: "Was macht die Schnecke bei Gefahr?", a: ["Sie zieht sich ins Haus zurück.", "Sie rennt schnell weg.", "Sie fliegt davon.", "Sie beißt zu."] },
        { text: "Der Frosch sitzt am Rand des Teichs. Mit einem weiten Sprung fängt er eine Fliege. Seine lange Zunge ist blitzschnell.",
          q: "Womit fängt der Frosch die Fliege?", a: ["Mit seiner Zunge.", "Mit den Vorderpfoten.", "Mit dem Schwanz.", "Mit einem Netz."] },
        { text: "Die Ameisen tragen Blätter in ihren Bau. Gemeinsam schleppen sie schwere Lasten. Der Ameisenhaufen wird jeden Tag größer.",
          q: "Wie tragen die Ameisen die schweren Lasten?", a: ["Gemeinsam.", "Ganz allein.", "Mit einem Wagen.", "Sie tragen nichts."] },
      ] },
      { key: "leseAlltag", diff: 2, items: [
        { text: "Lena hat heute Geburtstag. Ihre Freunde bringen bunte Geschenke mit. Auf dem Tisch steht ein Kuchen mit acht Kerzen.",
          q: "Wie alt wird Lena wahrscheinlich?", a: ["Acht Jahre.", "Drei Jahre.", "Zwölf Jahre.", "Ein Jahr."] },
        { text: "Tom zieht seine Gummistiefel an. Draußen regnet es schon den ganzen Tag. Er springt gern in die tiefen Pfützen.",
          q: "Warum zieht Tom Gummistiefel an?", a: ["Weil es regnet.", "Weil die Sonne scheint.", "Weil es schneit.", "Weil es heiß ist."] },
        { text: "Opa backt am Sonntag frische Brötchen. Der ganze Flur riecht schon danach. Zum Frühstück gibt es sie mit Marmelade.",
          q: "Wann gibt es die Brötchen?", a: ["Zum Frühstück.", "Zum Abendessen.", "In der Nacht.", "Am Nachmittag."] },
        { text: "Mia hat ihre Sportschuhe vergessen. Ohne Schuhe darf sie nicht in die Halle. Heute muss sie beim Sport nur zuschauen.",
          q: "Warum darf Mia nicht mitmachen?", a: ["Sie hat ihre Sportschuhe vergessen.", "Sie ist krank.", "Sie hat keine Lust.", "Die Halle ist zu."] },
        { text: "Der Bus kommt jeden Morgen um acht. Heute steht Paul schon um Viertel vor acht da. Er will auf keinen Fall zu spät kommen.",
          q: "Warum ist Paul so früh da?", a: ["Er will den Bus nicht verpassen.", "Er mag den Busfahrer.", "Er ist noch müde.", "Er hat Hunger."] },
        { text: "In der Bücherei ist es ganz leise. Anna sucht ein Buch über Pferde. Die Frau am Tresen hilft ihr beim Suchen.",
          q: "Was für ein Buch sucht Anna?", a: ["Ein Buch über Pferde.", "Ein Buch über Autos.", "Ein Buch über Sterne.", "Einen Comic."] },
        { text: "Ben hat sich am Knie wehgetan. Die Mutter klebt ein Pflaster darauf. Nach ein paar Tagen tut es nicht mehr weh.",
          q: "Was macht die Mutter auf das Knie?", a: ["Ein Pflaster.", "Eine kalte Suppe.", "Einen Verband um den Kopf.", "Gar nichts."] },
        { text: "Die Ampel zeigt gerade Rot. Emma wartet geduldig am Straßenrand. Erst bei Grün geht sie über die Straße.",
          q: "Wann geht Emma über die Straße?", a: ["Bei Grün.", "Bei Rot.", "Bei Gelb.", "Sofort."] },
        { text: "Im Schwimmbad ruft der Bademeister laut. Am tiefen Becken darf nur schwimmen, wer es schon kann. Nele übt noch im flachen Wasser.",
          q: "Wo übt Nele?", a: ["Im flachen Wasser.", "Im tiefen Becken.", "Auf dem Sprungturm.", "In der Rutsche."] },
        { text: "Der Zahnarzt schaut sich Jonas Zähne an. Ganz vorne wackelt ein Milchzahn. Bald fällt er aus und ein neuer wächst nach.",
          q: "Was passiert mit dem wackelnden Zahn?", a: ["Er fällt bald aus.", "Er bleibt für immer.", "Er wird golden.", "Er wächst zusammen."] },
        { text: "Sara pflanzt eine Bohne in einen Topf. Jeden Tag gießt sie ein bisschen Wasser. Nach einer Woche schaut ein grüner Keim heraus.",
          q: "Was muss Sara jeden Tag tun?", a: ["Die Bohne gießen.", "Den Topf umstellen.", "Die Erde wechseln.", "Die Bohne ausgraben."] },
        { text: "Der Brief soll zu Oma nach Hamburg. Papa klebt eine Briefmarke darauf. Dann wirft Finn ihn in den gelben Kasten.",
          q: "Wohin wirft Finn den Brief?", a: ["In den Briefkasten.", "In den Mülleimer.", "In die Schultasche.", "Ins Bücherregal."] },
      ] },
      { key: "leseNatur", diff: 2, items: [
        { text: "Aus dem kleinen Samen wächst ein Baum. Zuerst kommt ein zarter grüner Trieb. Nach vielen Jahren ist er hoch und stark.",
          q: "Was wächst aus dem Samen?", a: ["Ein Baum.", "Ein Stein.", "Ein Pilz.", "Ein Vogel."] },
        { text: "Am Morgen liegt Tau auf dem Gras. Die Sonne steigt langsam höher. Bald sind die feuchten Tropfen verschwunden.",
          q: "Warum verschwinden die Tropfen?", a: ["Die Sonne trocknet sie.", "Der Wind weht sie weg.", "Die Vögel trinken sie.", "Es wird kälter."] },
        { text: "Der Regen fällt aus den grauen Wolken. Er füllt die Bäche und Flüsse. Die Pflanzen trinken das Wasser aus dem Boden.",
          q: "Woher kommt der Regen?", a: ["Aus den Wolken.", "Aus dem Fluss.", "Aus der Erde.", "Aus dem Brunnen."] },
        { text: "Im Winter ist der See zugefroren. Eine dicke Eisschicht liegt auf dem Wasser. Im Frühling schmilzt das Eis wieder.",
          q: "Was passiert mit dem Eis im Frühling?", a: ["Es schmilzt.", "Es wird dicker.", "Es bleibt gleich.", "Es wird bunt."] },
        { text: "Der Wind treibt die Wolken über den Himmel. Manchmal sehen sie aus wie Tiere. Am Abend werden sie ganz rosa.",
          q: "Was treibt die Wolken?", a: ["Der Wind.", "Die Sonne.", "Der Regen.", "Die Vögel."] },
        { text: "Ein Gewitter zieht über das Land. Zuerst blitzt es hell am Himmel. Kurz danach hört man den lauten Donner.",
          q: "Was kommt zuerst, Blitz oder Donner?", a: ["Der Blitz.", "Der Donner.", "Beide zusammen.", "Der Regen."] },
        { text: "Im Frühling blühen die Apfelbäume weiß. Die Bienen holen sich den süßen Nektar. Später wachsen daraus die roten Äpfel.",
          q: "Was wächst später aus den Blüten?", a: ["Äpfel.", "Nüsse.", "Blätter.", "Kirschen."] },
        { text: "Der Herbstwind schüttelt die Bäume. Die bunten Blätter fallen zu Boden. Bald sind die Äste ganz kahl.",
          q: "Was passiert mit den Blättern im Herbst?", a: ["Sie fallen zu Boden.", "Sie werden wieder grün.", "Sie wachsen nach.", "Sie fliegen in den Süden."] },
        { text: "Die Sonnenblume dreht sich nach der Sonne. Am Morgen schaut sie nach Osten. Am Abend blickt ihr Kopf nach Westen.",
          q: "Wonach dreht sich die Sonnenblume?", a: ["Nach der Sonne.", "Nach dem Wind.", "Nach dem Regen.", "Nach dem Mond."] },
        { text: "Nach dem Regen kriecht der Regenwurm heraus. Er lockert mit seinen Gängen die Erde. So bekommen die Wurzeln mehr Luft.",
          q: "Was macht der Regenwurm für die Erde?", a: ["Er lockert sie auf.", "Er macht sie hart.", "Er frisst die Wurzeln.", "Er trocknet sie aus."] },
        { text: "Im Teich schwimmen kleine Kaulquappen. Sie haben noch keinen Frosch-Körper. Erst wachsen ihnen Beine, dann springen sie an Land.",
          q: "Was werden aus den Kaulquappen?", a: ["Frösche.", "Fische.", "Enten.", "Libellen."] },
        { text: "Der Ahornbaum lässt seine Samen fallen. Sie drehen sich wie kleine Hubschrauber. Der Wind trägt sie weit über die Wiese.",
          q: "Wie fallen die Ahornsamen?", a: ["Sie drehen sich wie Hubschrauber.", "Sie fallen wie schwere Steine.", "Sie schweben wie Ballons.", "Sie hüpfen wie Bälle."] },
      ] },
      { key: "leseAbenteuer", diff: 2, items: [
        { text: "Der Kapitän steuert das Schiff über das Meer. Am Horizont taucht eine kleine Insel auf. Die Möwen begleiten das Boot zum Hafen.",
          q: "Was taucht am Horizont auf?", a: ["Eine Insel.", "Ein Wal.", "Ein Sturm.", "Ein anderes Schiff."] },
        { text: "Die Forscherin klettert den hohen Berg hinauf. Der Schnee glitzert in der Sonne. Ganz oben weht eine steife, kalte Brise.",
          q: "Wie ist das Wetter oben auf dem Berg?", a: ["Kalt und windig.", "Warm und sonnig.", "Regnerisch.", "Neblig und still."] },
        { text: "Im Zelt ist es nachts ganz dunkel. Max hört draußen eine Eule rufen. Mit der Taschenlampe fühlt er sich gleich mutiger.",
          q: "Was hört Max in der Nacht?", a: ["Eine Eule.", "Einen Wolf.", "Den Regen.", "Ein Auto."] },
        { text: "Die Taucherin gleitet durch das blaue Wasser. Bunte Fische schwimmen um sie herum. An den Felsen wächst rote Koralle.",
          q: "Was wächst an den Felsen?", a: ["Koralle.", "Gras.", "Blumen.", "Moos."] },
        { text: "Der Pilot hebt mit dem Flugzeug ab. Unter ihm werden die Häuser winzig klein. Über den Wolken scheint die helle Sonne.",
          q: "Wie sehen die Häuser von oben aus?", a: ["Ganz klein.", "Sehr groß.", "Bunt bemalt.", "Ganz kaputt."] },
        { text: "Die Wüste ist heiß und voller Sand. Ein Kamel trägt den Reiter durch die Dünen. Erst am Abend wird es angenehm kühl.",
          q: "Wann wird es in der Wüste kühl?", a: ["Am Abend.", "Am Mittag.", "Am Morgen.", "Niemals."] },
        { text: "Tief in der Höhle ist es stockdunkel. Von der Decke hängen spitze Zapfen aus Stein. Wassertropfen fallen langsam herab.",
          q: "Wie ist es tief in der Höhle?", a: ["Stockdunkel.", "Sonnig hell.", "Warm und trocken.", "Laut und bunt."] },
        { text: "Die Astronautin schwebt in der Raumstation. Ohne Schwerkraft fliegt alles durch die Luft. Durch das Fenster sieht sie die runde Erde.",
          q: "Warum schwebt in der Raumstation alles?", a: ["Es gibt keine Schwerkraft.", "Es ist zu heiß.", "Der Wind bläst stark.", "Der Boden ist glatt."] },
        { text: "Der Bergführer geht voran durch den tiefen Schnee. An einem Seil sind alle miteinander verbunden. So kann niemand verloren gehen.",
          q: "Warum sind alle mit einem Seil verbunden?", a: ["Damit niemand verloren geht.", "Damit es schneller geht.", "Damit es warm bleibt.", "Nur zum Spielen."] },
        { text: "Im Dschungel ist es feucht und grün. Bunte Papageien kreischen in den Bäumen. Eine Affenbande schwingt von Ast zu Ast.",
          q: "Wie bewegen sich die Affen?", a: ["Sie schwingen von Ast zu Ast.", "Sie fliegen hoch.", "Sie schwimmen im Fluss.", "Sie graben sich ein."] },
        { text: "Das U-Boot taucht tief ins dunkle Meer. Durch das Fenster leuchten seltsame Fische. Ganz unten ist es kalt und still.",
          q: "Wie ist es ganz unten im Meer?", a: ["Kalt und still.", "Warm und laut.", "Hell und bunt.", "Trocken und windig."] },
        { text: "Der Ballon steigt langsam in die Höhe. Mit heißer Luft wird er nach oben getragen. Unter dem Korb wird die Stadt immer kleiner.",
          q: "Was trägt den Ballon nach oben?", a: ["Heiße Luft.", "Ein starker Motor.", "Ein langes Seil.", "Große Vögel."] },
      ] },
    ],
  },
};

// How many items a language holds — the length of its box digit string (§14.5).
export function itemCount(lang = "de") {
  return CONTENT[lang].packs.reduce((n, p) => n + p.items.length, 0);
}
