// Lesen content (§14.2). Data only — no logic, no DOM.
//
// Canonical item order for the box digit string (§9.2): packs in this array's
// order, items in theirs. NEVER reorder or delete an entry — append only, or
// every child's Leitner boxes shift under her. New content is therefore added
// at the END of this file, as `extends` packs (see below).
//
// Deeper tiles (§14.3): a pack with an `extends: "<primaryKey>"` field is not a
// tile of its own — it is more items poured into that primary tile's pool, same
// theme, drawn in the same round. It carries the same `diff` and one `key` of
// its own, and lives at the end of the file so it appends without shifting any
// existing id. This is how a themed tile grows past its original ten or twelve
// items without touching the reward economy (the tile count, and so maxPoints
// and the trophy ladder, stay put — logic.js `packsFor`/`poolFor`).
//
// Authoring rules (enforced by tests/lesen-content.test.js):
//  - a Leicht item is a word `{ w, e }` with ONE unambiguous, mainstream emoji;
//    inside a pack, words and emoji are unique, and no two emoji are near-twins
//    (🐶 vs 🐺 is fine, 🐶 vs 🐕 is a bug) — distractors are drawn from the same
//    pack (§14.3);
//  - a Mittel item is a Stimmt/Blödsinn pair `{ ok, no }`: `ok` a true sentence,
//    `no` a nonsense one on the same theme, each ≤ 60 chars and ending ".", the
//    two faces distinct and every sentence unique game-wide. questionFor shows
//    one of the two per encounter, so the verdict cannot be memorised (§14.1);
//  - a Schwer item is a reading passage `{ text, q, a }`: `text` is a short
//    passage (~3 lines, ≤ 175 chars, sentences ending "."), `q` a question
//    ending "?", and `a` FOUR distinct answers with the CORRECT one FIRST
//    (optionsFor shuffles them). The three wrong answers are plausible but
//    clearly wrong to someone who READ the passage — the point is comprehension,
//    not a guess (§14.2).
//
// German only for now; an English set is a later milestone (§14.6) and slots
// in as a second key beside `de`.
export const CONTENT = {
  de: {
    packs: [
      // --- Leicht: short frequent words, 1–2 syllables, 10 each ---
      { key: "tiere", diff: 0, items: [
        { w: "Hund", e: "🐶" },
        { w: "Katze", e: "🐱" },
        { w: "Maus", e: "🐭" },
        { w: "Fisch", e: "🐟" },
        { w: "Vogel", e: "🐦" },
        { w: "Pferd", e: "🐴" },
        { w: "Kuh", e: "🐮" },
        { w: "Schwein", e: "🐷" },
        { w: "Frosch", e: "🐸" },
        { w: "Ente", e: "🦆" },
      ] },
      { key: "essen", diff: 0, items: [
        { w: "Brot", e: "🍞" },
        { w: "Apfel", e: "🍎" },
        { w: "Eis", e: "🍦" },
        { w: "Käse", e: "🧀" },
        { w: "Pizza", e: "🍕" },
        { w: "Banane", e: "🍌" },
        { w: "Ei", e: "🥚" },
        { w: "Milch", e: "🥛" },
        { w: "Keks", e: "🍪" },
        { w: "Honig", e: "🍯" },
      ] },
      { key: "zuhause", diff: 0, items: [
        { w: "Bett", e: "🛏️" },
        { w: "Buch", e: "📖" },
        { w: "Tür", e: "🚪" },
        { w: "Uhr", e: "🕐" },
        { w: "Lampe", e: "💡" },
        { w: "Schere", e: "✂️" },
        { w: "Stuhl", e: "🪑" },
        { w: "Seife", e: "🧼" },
        { w: "Besen", e: "🧹" },
        { w: "Schlüssel", e: "🔑" },
      ] },
      { key: "natur", diff: 0, items: [
        { w: "Baum", e: "🌳" },
        { w: "Sonne", e: "☀️" },
        { w: "Mond", e: "🌙" },
        { w: "Stern", e: "🌟" },
        { w: "Blume", e: "🌸" },
        { w: "Wolke", e: "☁️" },
        { w: "Feuer", e: "🔥" },
        { w: "Berg", e: "⛰️" },
        { w: "Pilz", e: "🍄" },
        { w: "Blatt", e: "🍁" },
      ] },
      // --- Mittel: Stimmt/Quatsch (§14.1) — one whole sentence to read and a
      // verdict to give. Each item is a `{ ok, no }` pair: `ok` is a true
      // sentence, `no` a nonsense one on the same theme, and questionFor draws
      // one of the two per encounter, so the child cannot memorise "the fourth
      // one is true" — she has to read it. Rewritten IN PLACE from the old
      // Mittel word packs (their pack keys are unchanged, so their i18n names
      // and every child's Leitner box position stay put — §9.2). 10 pairs each. ---
      { key: "tierwelt", diff: 1, items: [
        { ok: "Ein Pinguin kann gut schwimmen.", no: "Ein Pinguin fährt gern Fahrrad." },
        { ok: "Der Elefant hat einen langen Rüssel.", no: "Der Elefant schläft in einem Vogelnest." },
        { ok: "Eine Schildkröte trägt ihr Haus mit sich.", no: "Eine Schildkröte rennt schneller als ein Auto." },
        { ok: "Das Krokodil hat viele scharfe Zähne.", no: "Das Krokodil strickt sich einen warmen Schal." },
        { ok: "Ein Papagei kann Wörter nachsprechen.", no: "Ein Papagei taucht tief auf den Meeresgrund." },
        { ok: "Der Delfin lebt im Meer.", no: "Der Delfin wohnt in einem Baumhaus." },
        { ok: "Das Känguru hüpft mit großen Sprüngen.", no: "Das Känguru schläft kopfüber an der Decke." },
        { ok: "Ein Schmetterling hat bunte Flügel.", no: "Ein Schmetterling zieht einen schweren Anhänger." },
        { ok: "Das Eichhörnchen sammelt gern Nüsse.", no: "Das Eichhörnchen spielt Trompete im Zirkus." },
        { ok: "Ein Marienkäfer hat rote Flügel mit Punkten.", no: "Ein Marienkäfer bellt laut wie ein Hund." },
      ] },
      { key: "unterwegs", diff: 1, items: [
        { ok: "Ein Flugzeug fliegt hoch am Himmel.", no: "Ein Flugzeug fährt unter Wasser zur Schule." },
        { ok: "Das Feuerwehrauto löscht das Feuer.", no: "Das Feuerwehrauto backt einen Kuchen." },
        { ok: "Ein Segelboot braucht Wind zum Fahren.", no: "Ein Segelboot fliegt bis zum Mond." },
        { ok: "Der Traktor arbeitet auf dem Feld.", no: "Der Traktor schläft in einem Bett." },
        { ok: "Eine Rakete fliegt in den Weltraum.", no: "Eine Rakete schwimmt gemütlich im Teich." },
        { ok: "Der Krankenwagen bringt Kranke ins Krankenhaus.", no: "Der Krankenwagen verkauft Eis am Strand." },
        { ok: "Ein Hubschrauber hat einen großen Rotor.", no: "Ein Hubschrauber gräbt sich unter die Erde." },
        { ok: "Die Straßenbahn fährt auf Schienen.", no: "Die Straßenbahn klettert auf hohe Bäume." },
        { ok: "Ein Fahrrad hat zwei Räder.", no: "Ein Fahrrad legt jeden Morgen ein Ei." },
        { ok: "Das Polizeiauto hat ein lautes Blaulicht.", no: "Das Polizeiauto wächst in einem Blumenbeet." },
      ] },
      { key: "kueche", diff: 1, items: [
        { ok: "Schokolade schmeckt süß.", no: "Schokolade schmeckt scharf wie Pfeffer." },
        { ok: "Eine Zitrone schmeckt sauer.", no: "Eine Zitrone schmeckt süß wie Honig." },
        { ok: "Eine Erdbeere ist rot und klein.", no: "Eine Erdbeere ist so groß wie ein Haus." },
        { ok: "Ein Spiegelei macht man aus einem Ei.", no: "Ein Spiegelei macht man aus Steinen." },
        { ok: "Die Wassermelone ist innen rot und saftig.", no: "Die Wassermelone ist innen voller Schrauben." },
        { ok: "Eine Brezel ist gebacken und salzig.", no: "Eine Brezel ist aus hartem Metall." },
        { ok: "Palatschinken bäckt man in der Pfanne.", no: "Palatschinken wachsen an hohen Bäumen." },
        { ok: "Eine Kartoffel wächst in der Erde.", no: "Eine Kartoffel fliegt wie ein Vogel." },
        { ok: "Eine Karotte ist orange und knackig.", no: "Eine Karotte leuchtet nachts wie eine Lampe." },
        { ok: "Auf den Geburtstagskuchen kommen Kerzen.", no: "Auf den Geburtstagskuchen kommt Zahnpasta." },
      ] },
      { key: "draussen", diff: 1, items: [
        { ok: "Ein Regenbogen hat viele Farben.", no: "Ein Regenbogen ist immer ganz schwarz." },
        { ok: "Bei einem Gewitter blitzt und donnert es.", no: "Bei einem Gewitter regnet es Bonbons." },
        { ok: "Einen Schneemann baut man aus Schnee.", no: "Einen Schneemann baut man aus warmem Sand." },
        { ok: "Eine Schneeflocke ist weiß und kalt.", no: "Eine Schneeflocke ist heiß wie Feuer." },
        { ok: "Ein Drachen steigt im Wind in die Luft.", no: "Ein Drachen fliegt tief unter der Erde." },
        { ok: "In einem Zelt kann man übernachten.", no: "In einem Zelt fährt man über das Meer." },
        { ok: "Einen Fußball tritt man mit dem Fuß.", no: "Einen Fußball isst man mit Messer und Gabel." },
        { ok: "Ein Luftballon ist mit Luft gefüllt.", no: "Ein Luftballon ist aus schwerem Stein." },
        { ok: "Eine Sonnenblume dreht sich zur Sonne.", no: "Eine Sonnenblume wächst kopfüber im Keller." },
        { ok: "Ein Regenschirm schützt vor dem Regen.", no: "Ein Regenschirm schützt vor lauter Musik." },
      ] },
      // --- Schwer: reading passages, comprehension question, 4 answers (§14.2).
      // `text` is a short passage (~3 lines), `q` the question, and `a` the four
      // options with the CORRECT one FIRST (optionsFor shuffles them). Rewritten
      // in place from the old Quatsch pairs: the item positions are unchanged, so
      // no child's Leitner box shifts (§9.2). The skill is comprehension now — a
      // 50/50 verdict rewarded guessing; four answers over a passage do not. ---
      { key: "leseTiere", diff: 2, items: [
        { text: "Der Igel tapst nachts durch den Garten und schnauft dabei wie eine kleine Lokomotive. Er sucht Käfer und Würmer. Am Tag schnarcht er unter den Blättern.",
          q: "Wann sucht der Igel sein Futter?", a: ["In der Nacht.", "Am Morgen.", "Am Mittag.", "Am Nachmittag."] },
        { text: "Klecks für Klecks pappt die Schwalbe ihr Nest aus Lehm an die Hauswand. Es sieht aus wie ein Matschklumpen. Doch darin sind die Küken sicher vor der Katze.",
          q: "Woraus baut die Schwalbe ihr Nest?", a: ["Aus Lehm.", "Aus Stroh.", "Aus Federn.", "Aus Papier."] },
        { text: "Der Biber nagt einen ganzen Baum mit den Zähnen um — ganz ohne Säge! Aus den Ästen baut er einen Damm. So staut sich der Fluss zu einem Teich.",
          q: "Womit fällt der Biber die Bäume?", a: ["Mit seinen Zähnen.", "Mit einer Säge.", "Mit den Pfoten.", "Mit dem Schwanz."] },
        { text: "Im Herbst versteckt das Eichhörnchen überall Nüsse und vergisst dann die Hälfte davon. Im Winter sucht es und findet nicht alle wieder. Manche wird sogar zu einem Baum.",
          q: "Warum findet es im Winter nicht alle Nüsse?", a: ["Es hat die Verstecke vergessen.", "Es hat keinen Hunger.", "Der Bär hat sie gefressen.", "Es schläft den ganzen Winter."] },
        { text: "Am Tag hängt die Fledermaus kopfüber in der Höhle und schläft wie ein zusammengeklappter Regenschirm. Erst wenn es dunkel wird, saust sie los und schnappt Mücken.",
          q: "Wie schläft die Fledermaus?", a: ["Kopfüber.", "Im Nest.", "Auf dem Rücken.", "Im Wasser."] },
        { text: "Der junge Storch übt auf dem Dach das Fliegen und wackelt dabei ganz schön. Im Sommer ist er noch zu tapsig für die weite Reise. Im Herbst geht es in den warmen Süden.",
          q: "Wann fliegt der Storch in den Süden?", a: ["Im Herbst.", "Im Sommer.", "Im Winter.", "Im Frühling."] },
        { text: "Die Biene tanzt von Blüte zu Blüte und schleppt süßen Nektar im Bauch nach Hause. Im Bienenstock rühren alle kräftig mit. Am Ende ist daraus goldener Honig geworden.",
          q: "Was machen die Bienen aus dem Nektar?", a: ["Honig.", "Wachs.", "Marmelade.", "Zucker."] },
        { text: "Der Delfin schwimmt im Meer, ist aber gar kein Fisch. Zum Atmen schießt er nach oben und pustet durch ein Loch am Kopf eine Fontäne. Dann taucht er wieder ab.",
          q: "Warum kommt der Delfin an die Oberfläche?", a: ["Um Luft zu holen.", "Um zu schlafen.", "Um Fische zu fangen.", "Um sich zu sonnen."] },
        { text: "Mit seinen breiten Schaufelpfoten gräbt der Maulwurf tief unter der Wiese lange Gänge. Sehen tut man ihn fast nie. Nur seine kleinen Erdhügel verraten, wo er war.",
          q: "Was sieht man vom Maulwurf draußen?", a: ["Kleine Erdhügel.", "Seine Pfoten.", "Sein Nest.", "Seine Augen."] },
        { text: "Die Schnecke trägt ihr Haus immer mit — praktisch, wenn es regnet! Kommt Gefahr, zieht sie sich blitzschnell hinein. Sonst kriecht sie gemütlich über das feuchte Blatt.",
          q: "Was macht die Schnecke bei Gefahr?", a: ["Sie zieht sich ins Haus zurück.", "Sie rennt schnell weg.", "Sie fliegt davon.", "Sie beißt zu."] },
        { text: "Der Frosch sitzt ganz still am Teich und tut, als würde er schlafen. Dann schnellt plötzlich seine lange Zunge heraus. Blitzschnell schnappt er sich damit eine Fliege.",
          q: "Womit fängt der Frosch die Fliege?", a: ["Mit seiner Zunge.", "Mit den Vorderpfoten.", "Mit dem Schwanz.", "Mit einem Netz."] },
        { text: "Die Ameise ist winzig, aber unglaublich stark. Gemeinsam schleppt das Volk Blätter, die viel schwerer sind als sie selbst. So wird der Ameisenhaufen jeden Tag größer.",
          q: "Wie tragen die Ameisen die schweren Lasten?", a: ["Gemeinsam.", "Ganz allein.", "Mit einem Wagen.", "Sie tragen nichts."] },
      ] },
      { key: "leseAlltag", diff: 2, items: [
        { text: "Heute hat Lena Geburtstag und strahlt über das ganze Gesicht. Ihre Freunde bringen bunte Geschenke mit. Auf dem Kuchen brennen acht Kerzen, die sie mit einem Puster ausbläst.",
          q: "Wie alt wird Lena wahrscheinlich?", a: ["Acht Jahre.", "Drei Jahre.", "Zwölf Jahre.", "Ein Jahr."] },
        { text: "Draußen schüttet es seit Stunden. Tom zieht seine Gummistiefel an und grinst. Denn nichts macht mehr Spaß, als mit einem lauten Platsch in die tiefsten Pfützen zu springen.",
          q: "Warum zieht Tom Gummistiefel an?", a: ["Weil es regnet.", "Weil die Sonne scheint.", "Weil es schneit.", "Weil es heiß ist."] },
        { text: "Am Sonntag bäckt Opa frische Semmeln, und der Duft weckt die ganze Familie. Alle schleichen in die Küche. Zum Frühstück gibt es die warmen Semmeln mit Marmelade.",
          q: "Wann gibt es die Semmeln?", a: ["Zum Frühstück.", "Zum Abendessen.", "In der Nacht.", "Am Nachmittag."] },
        { text: "In der Eile hat Mia ihre Sportschuhe zu Hause vergessen — ausgerechnet heute! Ohne Schuhe darf sie nicht in die Halle. Also muss sie beim Turnen von der Bank aus zuschauen.",
          q: "Warum darf Mia nicht mitmachen?", a: ["Sie hat ihre Sportschuhe vergessen.", "Sie ist krank.", "Sie hat keine Lust.", "Die Halle ist zu."] },
        { text: "Gestern hat Paul den Bus um Haaresbreite verpasst — das passiert ihm nie wieder! Heute steht er schon um Viertel vor acht an der Haltestelle. Der Bus kommt aber erst um acht.",
          q: "Warum ist Paul so früh da?", a: ["Er will den Bus nicht verpassen.", "Er mag den Busfahrer.", "Er ist noch müde.", "Er hat Hunger."] },
        { text: "In der Bücherei muss man ganz leise sein — nur das Blättern raschelt. Anna sucht ein Buch über Pferde. Die freundliche Frau am Pult zieht ihr das dickste aus dem Regal.",
          q: "Was für ein Buch sucht Anna?", a: ["Ein Buch über Pferde.", "Ein Buch über Autos.", "Ein Buch über Sterne.", "Einen Comic."] },
        { text: "Beim Fangenspielen ist Ben hingefallen und hat sich das Knie aufgeschürft. Die Mama pustet kurz und klebt ein buntes Pflaster darauf. Nach ein paar Tagen tut nichts mehr weh.",
          q: "Was macht die Mama auf das Knie?", a: ["Ein Pflaster.", "Eine kalte Suppe.", "Einen Verband um den Kopf.", "Gar nichts."] },
        { text: "Die Ampel zeigt Rot, und Emma zappelt ungeduldig am Straßenrand. Am liebsten würde sie sofort los. Doch sie weiß es besser und geht erst bei Grün über die Straße.",
          q: "Wann geht Emma über die Straße?", a: ["Bei Grün.", "Bei Rot.", "Bei Gelb.", "Sofort."] },
        { text: "Im Schwimmbad ruft der Bademeister streng: Ins tiefe Becken darf nur, wer schon schwimmen kann! Nele paddelt noch im flachen Wasser und übt jeden Tag ein bisschen mehr.",
          q: "Wo übt Nele?", a: ["Im flachen Wasser.", "Im tiefen Becken.", "Auf dem Sprungturm.", "In der Rutsche."] },
        { text: "Beim Zahnarzt entdeckt Jonas: Ganz vorne wackelt ein Zahn hin und her! Mit der Zunge stupst er ihn ständig an. Bald fällt der Milchzahn aus und ein neuer wächst nach.",
          q: "Was passiert mit dem wackelnden Zahn?", a: ["Er fällt bald aus.", "Er bleibt für immer.", "Er wird golden.", "Er wächst zusammen."] },
        { text: "Sara steckt eine Bohne in einen Topf voll Erde. Jeden Tag gibt sie ihr ein Schlückchen Wasser und redet ihr gut zu. Nach einer Woche lugt ein grüner Keim heraus.",
          q: "Was muss Sara jeden Tag tun?", a: ["Die Bohne gießen.", "Den Topf umstellen.", "Die Erde wechseln.", "Die Bohne ausgraben."] },
        { text: "Der Brief soll zu Oma reisen. Papa klebt eine Briefmarke drauf, und Finn darf ihn einwerfen. Mit einem Quietschen schnappt der gelbe Briefkasten den Brief und verschluckt ihn.",
          q: "Wohin wirft Finn den Brief?", a: ["In den Briefkasten.", "In den Mülleimer.", "In die Schultasche.", "Ins Bücherregal."] },
      ] },
      { key: "leseNatur", diff: 2, items: [
        { text: "Aus einem winzigen Samen, kleiner als eine Erbse, wächst ein riesiger Baum. Zuerst schaut nur ein zarter grüner Trieb heraus. Nach vielen Jahren ist er hoch und stark.",
          q: "Was wächst aus dem Samen?", a: ["Ein Baum.", "Ein Stein.", "Ein Pilz.", "Ein Vogel."] },
        { text: "Am frühen Morgen glitzert der Tau wie tausend kleine Diamanten im Gras. Doch dann steigt die Sonne höher und höher. Bald hat sie die feuchten Tropfen weggetrocknet.",
          q: "Warum verschwinden die Tropfen?", a: ["Die Sonne trocknet sie.", "Der Wind weht sie weg.", "Die Vögel trinken sie.", "Es wird kälter."] },
        { text: "Die grauen Wolken werden immer dicker, bis sie platzen: Es regnet! Das Wasser füllt Bäche und Flüsse bis zum Rand. Die durstigen Pflanzen trinken es aus dem Boden.",
          q: "Woher kommt der Regen?", a: ["Aus den Wolken.", "Aus dem Fluss.", "Aus der Erde.", "Aus dem Brunnen."] },
        { text: "Im Winter ist der See steinhart gefroren, fast könnte man darauf tanzen. Eine dicke Eisschicht deckt das Wasser zu. Doch im Frühling wird es warm und das Eis schmilzt.",
          q: "Was passiert mit dem Eis im Frühling?", a: ["Es schmilzt.", "Es wird dicker.", "Es bleibt gleich.", "Es wird bunt."] },
        { text: "Der Wind schiebt die Wolken über den Himmel wie eine große Schafherde. Manchmal sehen sie aus wie Drachen oder Hasen. Am Abend färbt die Sonne sie ganz rosa.",
          q: "Was treibt die Wolken?", a: ["Der Wind.", "Die Sonne.", "Der Regen.", "Die Vögel."] },
        { text: "Ein Gewitter zieht auf, und alle Tiere verstecken sich. Zuerst zuckt ein greller Blitz über den Himmel. Erst ein paar Sekunden später grollt der laute Donner hinterher.",
          q: "Was kommt zuerst, Blitz oder Donner?", a: ["Der Blitz.", "Der Donner.", "Beide zusammen.", "Der Regen."] },
        { text: "Im Frühling stehen die Apfelbäume in weißen Blüten wie in einem Brautkleid. Die Bienen naschen den süßen Nektar. Aus den Blüten werden später die dicken roten Äpfel.",
          q: "Was wächst später aus den Blüten?", a: ["Äpfel.", "Nüsse.", "Blätter.", "Kirschen."] },
        { text: "Der Herbstwind rüttelt kräftig an den Bäumen. Die bunten Blätter lassen los und segeln zu Boden. Bald stehen die Äste kahl da und frieren im ersten Frost.",
          q: "Was passiert mit den Blättern im Herbst?", a: ["Sie fallen zu Boden.", "Sie werden wieder grün.", "Sie wachsen nach.", "Sie fliegen in den Süden."] },
        { text: "Die Sonnenblume ist eine echte Sonnenanbeterin. Am Morgen dreht sie ihr Gesicht nach Osten. Den ganzen Tag folgt sie der Sonne, bis ihr Kopf am Abend nach Westen schaut.",
          q: "Wonach dreht sich die Sonnenblume?", a: ["Nach der Sonne.", "Nach dem Wind.", "Nach dem Regen.", "Nach dem Mond."] },
        { text: "Nach dem Regen kriecht der Regenwurm aus dem Boden — sonst würde er unten ertrinken! Beim Graben lockert er die Erde auf. So bekommen die Wurzeln der Pflanzen mehr Luft.",
          q: "Was macht der Regenwurm für die Erde?", a: ["Er lockert sie auf.", "Er macht sie hart.", "Er frisst die Wurzeln.", "Er trocknet sie aus."] },
        { text: "Im Teich wuseln kleine Kaulquappen mit langen Schwänzen herum. Sie sehen noch gar nicht wie Frösche aus. Doch nach und nach wachsen ihnen Beine, und sie hüpfen an Land.",
          q: "Was werden aus den Kaulquappen?", a: ["Frösche.", "Fische.", "Enten.", "Libellen."] },
        { text: "Der Ahorn lässt seine Samen los, und sie trudeln wie kleine Hubschrauber durch die Luft. Der Wind trägt sie weit über die Wiese. Dort wächst weit weg vom Baum ein neuer Ahorn.",
          q: "Wie fallen die Ahornsamen?", a: ["Sie drehen sich wie Hubschrauber.", "Sie fallen wie schwere Steine.", "Sie schweben wie Ballons.", "Sie hüpfen wie Bälle."] },
      ] },
      { key: "leseAbenteuer", diff: 2, items: [
        { text: "Der Kapitän steuert sein Schiff über das Meer, als er plötzlich ruft: Land in Sicht! Am Horizont taucht eine kleine Insel auf. Möwen begleiten das Boot zum Hafen.",
          q: "Was taucht am Horizont auf?", a: ["Eine Insel.", "Ein Wal.", "Ein Sturm.", "Ein anderes Schiff."] },
        { text: "Stunde um Stunde klettert die Forscherin den Berg hinauf. Der Schnee funkelt in der Sonne. Ganz oben pfeift ihr ein eiskalter Wind um die Ohren, doch sie hat es geschafft.",
          q: "Wie ist das Wetter oben auf dem Berg?", a: ["Kalt und windig.", "Warm und sonnig.", "Regnerisch.", "Neblig und still."] },
        { text: "Im Zelt ist es nachts stockdunkel, und Max' Herz klopft laut. Draußen ruft etwas: Huhu, huhu! Mit der Taschenlampe traut er sich hinaus — puh, es ist nur eine Eule.",
          q: "Was hört Max in der Nacht?", a: ["Eine Eule.", "Einen Wolf.", "Den Regen.", "Ein Auto."] },
        { text: "Lautlos gleitet die Taucherin durch das blaue Wasser wie ein Fisch. Bunte Schwärme flitzen um sie herum. An den Felsen leuchtet rote Koralle, schön wie ein Blumengarten.",
          q: "Was wächst an den Felsen?", a: ["Koralle.", "Gras.", "Blumen.", "Moos."] },
        { text: "Der Pilot gibt Gas, und das Flugzeug hebt ab. Lea staunt aus dem Fenster: Unter ihr werden die Häuser winzig klein wie Spielzeug. Über den Wolken scheint die helle Sonne.",
          q: "Wie sehen die Häuser von oben aus?", a: ["Ganz klein.", "Sehr groß.", "Bunt bemalt.", "Ganz kaputt."] },
        { text: "In der Wüste brennt die Sonne heiß auf den Sand. Geduldig trägt ein Kamel den Reiter über die riesigen Dünen. Erst am Abend, wenn die Sonne sinkt, wird es angenehm kühl.",
          q: "Wann wird es in der Wüste kühl?", a: ["Am Abend.", "Am Mittag.", "Am Morgen.", "Niemals."] },
        { text: "Tief in der Höhle ist es stockdunkel und totenstill. Von der Decke hängen spitze Zapfen aus Stein wie steinerne Zähne. Ab und zu tropft es geheimnisvoll von oben herab.",
          q: "Wie ist es tief in der Höhle?", a: ["Stockdunkel.", "Sonnig hell.", "Warm und trocken.", "Laut und bunt."] },
        { text: "In der Raumstation schwebt die Astronautin wie ein Luftballon durch die Luft. Ohne Schwerkraft fliegt sogar ihr Frühstück davon! Durch das Fenster sieht sie die runde Erde.",
          q: "Warum schwebt in der Raumstation alles?", a: ["Es gibt keine Schwerkraft.", "Es ist zu heiß.", "Der Wind bläst stark.", "Der Boden ist glatt."] },
        { text: "Im tiefen Schnee stapft der Bergführer voran und sucht den sicheren Weg. Alle sind mit einem Seil verbunden wie Perlen an einer Kette. So geht im Schneesturm niemand verloren.",
          q: "Warum sind alle mit einem Seil verbunden?", a: ["Damit niemand verloren geht.", "Damit es schneller geht.", "Damit es warm bleibt.", "Nur zum Spielen."] },
        { text: "Im Dschungel ist es heiß, feucht und knallgrün. Bunte Papageien kreischen aus voller Kehle. Eine freche Affenbande schwingt kreuz und quer von Ast zu Ast.",
          q: "Wie bewegen sich die Affen?", a: ["Sie schwingen von Ast zu Ast.", "Sie fliegen hoch.", "Sie schwimmen im Fluss.", "Sie graben sich ein."] },
        { text: "Das U-Boot taucht tiefer ins dunkle Meer, bis kein Sonnenstrahl mehr hinreicht. Durch das Fenster leuchten Fische wie kleine Lampen. Ganz unten ist es eiskalt und still.",
          q: "Wie ist es ganz unten im Meer?", a: ["Kalt und still.", "Warm und laut.", "Hell und bunt.", "Trocken und windig."] },
        { text: "Mit einem lauten Fauchen bläst der Brenner heiße Luft in den Ballon. Ganz langsam hebt der Korb vom Boden ab. Unter den staunenden Fahrgästen wird die Stadt immer kleiner.",
          q: "Was trägt den Ballon nach oben?", a: ["Heiße Luft.", "Ein starker Motor.", "Ein langes Seil.", "Große Vögel."] },
      ] },

      // === Extensions (§14.3, deeper tiles) ===================================
      // Each pack below `extends` a primary theme above: its items are poured
      // into that tile's pool, drawn in the same round, and NEVER shown as a
      // tile of their own. They live here at the END of the file so no existing
      // item's id shifts (append-only). One extension per theme, same size as
      // its primary — so every tile holds twice the content it did, and a round
      // of eight now samples from a much larger well without repeating (§7.3).
      { key: "tiereB", diff: 0, extends: "tiere", items: [
        { w: "Löwe", e: "🦁" },
        { w: "Bär", e: "🐻" },
        { w: "Affe", e: "🐵" },
        { w: "Igel", e: "🦔" },
        { w: "Fuchs", e: "🦊" },
        { w: "Eule", e: "🦉" },
        { w: "Biene", e: "🐝" },
        { w: "Schaf", e: "🐑" },
        { w: "Ziege", e: "🐐" },
        { w: "Hase", e: "🐰" },
      ] },
      { key: "essenB", diff: 0, extends: "essen", items: [
        { w: "Traube", e: "🍇" },
        { w: "Birne", e: "🍐" },
        { w: "Kirsche", e: "🍒" },
        { w: "Erdbeere", e: "🍓" },
        { w: "Karotte", e: "🥕" },
        { w: "Tomate", e: "🍅" },
        { w: "Gurke", e: "🥒" },
        { w: "Suppe", e: "🍲" },
        { w: "Nudeln", e: "🍝" },
        { w: "Kuchen", e: "🍰" },
      ] },
      { key: "zuhauseB", diff: 0, extends: "zuhause", items: [
        { w: "Tasse", e: "☕" },
        { w: "Löffel", e: "🥄" },
        { w: "Teller", e: "🍽️" },
        { w: "Kerze", e: "🕯️" },
        { w: "Bild", e: "🖼️" },
        { w: "Koffer", e: "🧳" },
        { w: "Radio", e: "📻" },
        { w: "Handy", e: "📱" },
        { w: "Brille", e: "👓" },
        { w: "Eimer", e: "🪣" },
      ] },
      { key: "naturB", diff: 0, extends: "natur", items: [
        { w: "Regen", e: "🌧️" },
        { w: "Schnee", e: "❄️" },
        { w: "Blitz", e: "⚡" },
        { w: "Regenbogen", e: "🌈" },
        { w: "Tropfen", e: "💧" },
        { w: "Vulkan", e: "🌋" },
        { w: "Kaktus", e: "🌵" },
        { w: "Welle", e: "🌊" },
        { w: "Tornado", e: "🌪️" },
        { w: "Komet", e: "☄️" },
      ] },
      { key: "tierweltB", diff: 1, extends: "tierwelt", items: [
        { ok: "Ein Fisch atmet unter Wasser mit Kiemen.", no: "Ein Fisch klettert flink auf hohe Bäume." },
        { ok: "Die Eule kann in der Nacht gut sehen.", no: "Die Eule fährt jeden Morgen mit dem Bus." },
        { ok: "Der Bär hält im Winter einen langen Schlaf.", no: "Der Bär spielt im Winter gern Eishockey." },
        { ok: "Die Biene sammelt Nektar aus den Blüten.", no: "Die Biene näht sich abends warme Socken." },
        { ok: "Der Hase hat lange Ohren und hoppelt schnell.", no: "Der Hase trägt eine Brille und liest Zeitung." },
        { ok: "Eine Spinne webt ein feines Netz.", no: "Eine Spinne bläst große Seifenblasen." },
        { ok: "Der Wolf heult laut den Mond an.", no: "Der Wolf strickt Handschuhe für den Winter." },
        { ok: "Die Schnecke kriecht ganz langsam voran.", no: "Die Schnecke gewinnt jeden Sprint im Wettlauf." },
        { ok: "Der Adler fliegt hoch über die Berge.", no: "Der Adler gräbt sich tief in den Sand ein." },
        { ok: "Ein Maulwurf gräbt Gänge unter der Erde.", no: "Ein Maulwurf sonnt sich mittags am Pool." },
      ] },
      { key: "unterwegsB", diff: 1, extends: "unterwegs", items: [
        { ok: "Ein Zug fährt auf zwei langen Schienen.", no: "Ein Zug fliegt hoch über die Wolken." },
        { ok: "Das Motorrad hat zwei Räder und einen Motor.", no: "Das Motorrad wächst in einem Gemüsebeet." },
        { ok: "Ein U-Boot taucht tief unter das Wasser.", no: "Ein U-Boot rast schnell über die Autobahn." },
        { ok: "Der Bagger gräbt ein tiefes Loch.", no: "Der Bagger tanzt Ballett auf der Bühne." },
        { ok: "Ein Ballon steigt langsam in die Luft.", no: "Ein Ballon fährt tief unter der Erde." },
        { ok: "Der Lastwagen bringt schwere Kisten.", no: "Der Lastwagen passt in eine Hosentasche." },
        { ok: "Ein Kanu paddelt man mit den Armen.", no: "Ein Kanu fliegt mit großen Flügeln davon." },
        { ok: "Die Seilbahn fährt den Berg hinauf.", no: "Die Seilbahn kocht eine heiße Suppe." },
        { ok: "Ein Roller hat zwei Räder zum Stehen.", no: "Ein Roller brüllt laut wie ein Löwe." },
        { ok: "Ein Taxi bringt die Leute in die Stadt.", no: "Ein Taxi hüpft wie ein Frosch über den Zaun." },
      ] },
      { key: "kuecheB", diff: 1, extends: "kueche", items: [
        { ok: "Honig ist süß und klebrig.", no: "Honig ist hart wie ein Stein." },
        { ok: "Eine Zwiebel bringt uns zum Weinen.", no: "Eine Zwiebel schmeckt süß wie Zucker." },
        { ok: "Nudeln kocht man in heißem Wasser.", no: "Nudeln wachsen bunt auf der Wiese." },
        { ok: "Ein Apfel wächst an einem Baum.", no: "Ein Apfel schwimmt tief unten im Meer." },
        { ok: "Käse wird aus Milch gemacht.", no: "Käse wird aus grauen Steinen gemacht." },
        { ok: "Popcorn springt in der heißen Pfanne.", no: "Popcorn schläft ruhig in seinem Bett." },
        { ok: "Eine Banane ist krumm und gelb.", no: "Eine Banane ist eckig und blau." },
        { ok: "Brot backt der Bäcker im heißen Ofen.", no: "Brot baut der Bäcker aus Ziegelsteinen." },
        { ok: "Eis schmilzt in der warmen Sonne.", no: "Eis wird in der Sonne immer härter." },
        { ok: "Suppe isst man mit einem Löffel.", no: "Suppe isst man mit einer spitzen Schere." },
      ] },
      { key: "draussenB", diff: 1, extends: "draussen", items: [
        { ok: "Im Sandkasten baut man mit Sand.", no: "Im Sandkasten schwimmt man im tiefen Meer." },
        { ok: "Auf der Schaukel fliegt man hin und her.", no: "Auf der Schaukel schläft man tief und fest." },
        { ok: "Ein Igel rollt sich zu einer Kugel.", no: "Ein Igel fliegt abends bis zum Mond." },
        { ok: "Der Wind lässt den Drachen steigen.", no: "Der Wind malt bunte Bilder an die Wand." },
        { ok: "Aus der Wolke fällt kühler Regen.", no: "Aus der Wolke fallen kleine rote Autos." },
        { ok: "Im Herbst fallen die bunten Blätter.", no: "Im Herbst fallen die Blätter nach oben." },
        { ok: "Eine Pfütze ist voll mit Regenwasser.", no: "Eine Pfütze ist voll mit heißer Lava." },
        { ok: "Der Schneeball ist kalt und weiß.", no: "Der Schneeball ist heiß und feuerrot." },
        { ok: "Am Lagerfeuer wird es schön warm.", no: "Am Lagerfeuer wird es eiskalt wie im Eisschrank." },
        { ok: "Die Rutsche geht steil nach unten.", no: "Die Rutsche geht steil bis zu den Sternen." },
      ] },
      { key: "leseTiereB", diff: 2, extends: "leseTiere", items: [
        { text: "Der Pinguin watschelt tapsig über das Eis und plumpst dann auf den Bauch. So rutscht er viel schneller! Im Wasser wird er blitzschnell wie ein Torpedo.",
          q: "Wie rutscht der Pinguin schneller?", a: ["Auf dem Bauch.", "Auf dem Rücken.", "Auf einem Schlitten.", "Auf Schlittschuhen."] },
        { text: "Die Eule dreht ihren Kopf fast einmal ganz herum — huch! In der Nacht sieht sie messerscharf. Lautlos gleitet sie heran und schnappt sich eine Maus.",
          q: "Wann sieht die Eule besonders gut?", a: ["In der Nacht.", "Am Mittag.", "Am Morgen.", "Am Nachmittag."] },
        { text: "Der Specht hämmert mit dem Schnabel gegen den Stamm, dass es nur so knattert. Er sucht Käfer unter der Rinde. Sein harter Kopf tut ihm dabei nie weh.",
          q: "Warum hämmert der Specht gegen den Baum?", a: ["Er sucht Käfer.", "Er baut ein Haus.", "Er macht Musik.", "Er schärft den Schnabel."] },
        { text: "Das Krokodil liegt reglos im Wasser und sieht aus wie ein alter Baumstamm. Nur die Augen schauen heraus. Kommt ein Tier zu nah, schnappt es blitzschnell zu.",
          q: "Wie sieht das Krokodil im Wasser aus?", a: ["Wie ein Baumstamm.", "Wie ein Stein.", "Wie ein Fisch.", "Wie ein Boot."] },
        { text: "Das Kamel trägt seinen Proviant im Höcker mit sich herum. Tagelang braucht es kein Wasser. Durch den heißen Wüstensand stapft es ganz gemütlich.",
          q: "Was trägt das Kamel in seinem Höcker?", a: ["Seinen Proviant.", "Kühles Wasser.", "Weichen Sand.", "Ein warmes Nest."] },
        { text: "Die Giraffe ist so groß, dass sie an die höchsten Blätter kommt. Mit ihrer langen Zunge zupft sie sie ab. Nur zum Trinken muss sie sich tief hinunterbücken.",
          q: "Wie erreicht die Giraffe die höchsten Blätter?", a: ["Mit ihrer langen Zunge.", "Sie klettert hinauf.", "Sie fliegt hoch.", "Sie schüttelt den Baum."] },
        { text: "Der Wal ist das größte Tier der Welt, größer als ein Bus. Er lebt im Meer und singt tiefe Lieder. Zum Atmen bläst er eine hohe Fontäne in die Luft.",
          q: "Was macht der Wal zum Atmen?", a: ["Er bläst eine Fontäne.", "Er taucht tief hinab.", "Er springt an Land.", "Er singt ein Lied."] },
        { text: "Der Krebs läuft immer schön seitwärts über den Sand. Mit seinen kräftigen Scheren zwickt er ganz schön fest. Bei Gefahr huscht er flink unter einen Stein.",
          q: "Wie läuft der Krebs?", a: ["Seitwärts.", "Rückwärts.", "Im Kreis.", "Auf zwei Beinen."] },
        { text: "Der Marienkäfer hat leuchtend rote Flügel mit schwarzen Punkten. Blattläuse frisst er zum Frühstück, Mittag und Abend. Darum hat ihn jeder Gärtner gern.",
          q: "Was frisst der Marienkäfer am liebsten?", a: ["Blattläuse.", "Grüne Blätter.", "Süße Beeren.", "Kleine Steine."] },
        { text: "Die Spinne webt in der Nacht ein feines Netz zwischen zwei Ästen. Am Morgen glitzert es voll Tau. Bleibt eine Fliege kleben, hat die Spinne ihr Essen.",
          q: "Wozu baut die Spinne ihr Netz?", a: ["Um Fliegen zu fangen.", "Um darin zu schlafen.", "Um sich zu verstecken.", "Als Schaukel."] },
        { text: "Das Kängurubaby reitet gemütlich im Beutel seiner Mama mit. Dort ist es warm und sicher. Die Mama hüpft mit weiten Sprüngen über das ganze Land.",
          q: "Wo reitet das Kängurubaby mit?", a: ["Im Beutel der Mama.", "Auf dem Rücken.", "In einem Nest.", "In einer Höhle."] },
        { text: "Der bunte Papagei plappert alles nach, was er hört — sogar das Lachen! Mit dem krummen Schnabel knackt er harte Nüsse. Am liebsten sitzt er ganz oben im Baum.",
          q: "Was kann der Papagei besonders gut?", a: ["Wörter nachplappern.", "Schnell schwimmen.", "Tief graben.", "Hoch springen."] },
      ] },
      { key: "leseAlltagB", diff: 2, extends: "leseAlltag", items: [
        { text: "Klara lernt heute, ihre Schuhe selbst zu binden. Zuerst macht sie zwei Schlaufen wie Hasenohren. Nach vielen Versuchen klappt endlich die perfekte Schleife.",
          q: "Was lernt Klara heute?", a: ["Ihre Schuhe binden.", "Rad fahren.", "Schwimmen.", "Kochen."] },
        { text: "Am Abend putzt Felix zwei Minuten lang seine Zähne, bis sie glänzen. Er summt dabei sein Lieblingslied. So weiß er genau, wann die Zeit um ist.",
          q: "Wie merkt Felix, wann die Zeit um ist?", a: ["Sein Lied ist zu Ende.", "Die Uhr klingelt.", "Mama ruft ihn.", "Er wird müde."] },
        { text: "Dunkle Wolken ziehen auf, und Hanna schnappt sich schnell ihren Regenschirm. Kaum ist sie draußen, prasselt der Regen los. Trocken spaziert sie durch die Pfützen.",
          q: "Warum nimmt Hanna den Regenschirm mit?", a: ["Es sieht nach Regen aus.", "Die Sonne blendet.", "Es ist windig.", "Sie will spielen."] },
        { text: "Im Supermarkt schiebt Max den schweren Einkaufswagen. Auf dem Zettel stehen Milch, Brot und Äpfel. Konzentriert hakt er jedes Ding ab, das im Wagen landet.",
          q: "Was hilft Max beim Einkaufen?", a: ["Ein Einkaufszettel.", "Eine Landkarte.", "Ein Fernrohr.", "Ein Wecker."] },
        { text: "Bevor Lisa aufs Fahrrad steigt, setzt sie immer den Helm auf und macht ihn fest. Er schützt ihren Kopf, falls sie einmal stürzt. Dann tritt sie kräftig in die Pedale.",
          q: "Warum setzt Lisa den Helm auf?", a: ["Er schützt ihren Kopf.", "Er hält warm.", "Er sieht schön aus.", "Gegen die Sonne."] },
        { text: "Opa sucht überall seine Brille und wird schon ganz nervös. Er schaut unter dem Sofa und sogar im Kühlschrank nach. Dabei sitzt sie die ganze Zeit auf seiner Nase.",
          q: "Wo ist Opas Brille die ganze Zeit?", a: ["Auf seiner Nase.", "Unter dem Sofa.", "Im Kühlschrank.", "In der Tasche."] },
        { text: "Über Nacht hat es dick geschneit, und alles ist weiß. Nina zieht Mütze und Handschuhe an und baut einen großen Schneemann. Als Nase bekommt er eine Karotte.",
          q: "Was bekommt der Schneemann als Nase?", a: ["Eine Karotte.", "Einen Knopf.", "Einen Stein.", "Einen Ast."] },
        { text: "Tim kippt tausend Puzzleteile auf den Tisch. Erst sucht er alle Eckstücke heraus. Stück für Stück wächst ein bunter Dschungel voll wilder Tiere.",
          q: "Womit beginnt Tim beim Puzzeln?", a: ["Mit den Eckstücken.", "Mit der Mitte.", "Mit den Tieren.", "Mit dem Himmel."] },
        { text: "Sofie hilft der Oma beim Kekse backen. Mit Förmchen sticht sie Sterne und Herzen aus dem Teig. Warm aus dem Ofen duften sie durch die ganze Küche.",
          q: "Was macht Sofie mit den Förmchen?", a: ["Sterne und Herzen ausstechen.", "Den Teig rühren.", "Den Ofen anheizen.", "Die Kekse essen."] },
        { text: "Zum ersten Mal fährt Leon mit dem Zug zur Oma. Aufgeregt schaut er zu, wie Felder und Kühe vorbeisausen. Am Bahnhof winkt die Oma schon von Weitem.",
          q: "Wohin fährt Leon mit dem Zug?", a: ["Zur Oma.", "In die Schule.", "Ans Meer.", "In den Zoo."] },
        { text: "Beim Versteckspiel zählt Mara laut bis zwanzig. Die anderen huschen schnell hinter Büsche und Bäume. Dann ruft sie: Ich komme! und beginnt zu suchen.",
          q: "Was macht Mara, bevor sie sucht?", a: ["Sie zählt bis zwanzig.", "Sie versteckt sich.", "Sie schließt die Tür.", "Sie ruft die Eltern."] },
        { text: "Jeden Morgen gießt Jan die Blumen am Fenster. An heißen Tagen haben sie besonders großen Durst. Bekommen sie genug Wasser, blühen sie in kräftigen Farben.",
          q: "Wann haben die Blumen besonders Durst?", a: ["An heißen Tagen.", "An kalten Tagen.", "In der Nacht.", "Wenn es regnet."] },
      ] },
      { key: "leseNaturB", diff: 2, extends: "leseNatur", items: [
        { text: "Die dicke Raupe frisst tagelang Blätter, bis sie ganz rund ist. Dann spinnt sie sich in einen Kokon ein. Nach Wochen schlüpft daraus ein bunter Schmetterling.",
          q: "Was wird aus der Raupe?", a: ["Ein Schmetterling.", "Ein Käfer.", "Eine Fliege.", "Ein Vogel."] },
        { text: "Im Nest liegt ein glattes Ei, warm gehalten von der Henne. Innen wächst langsam ein Küken heran. Eines Tages pickt es die Schale auf und schlüpft heraus.",
          q: "Was schlüpft aus dem Ei?", a: ["Ein Küken.", "Ein Fisch.", "Eine Schlange.", "Ein Frosch."] },
        { text: "Am Abend klettert der helle Mond an den Himmel. Mal ist er rund wie ein Teller, mal nur eine schmale Sichel. Am Tag versteckt er sich vor der Sonne.",
          q: "Wie sieht der Mond manchmal aus?", a: ["Wie eine schmale Sichel.", "Wie ein Würfel.", "Wie ein Stern.", "Wie ein Herz."] },
        { text: "Im Frühling wird es endlich wärmer. Die ersten Blumen strecken ihre Köpfe aus der Erde. Überall zwitschern die Vögel und bauen fleißig ihre Nester.",
          q: "Was machen die Vögel im Frühling?", a: ["Sie bauen Nester.", "Sie fliegen in den Süden.", "Sie schlafen.", "Sie frieren."] },
        { text: "Nach dem Regen sprießen im Wald plötzlich viele Pilze aus dem Boden. Manche tragen einen roten Hut mit weißen Punkten. Doch Vorsicht, nicht jeder Pilz ist essbar.",
          q: "Wann sprießen die Pilze aus dem Boden?", a: ["Nach dem Regen.", "Im tiefsten Winter.", "Bei großer Hitze.", "Nur in der Nacht."] },
        { text: "Hoch in den Bergen entspringt ein kleiner Bach. Er plätschert bergab und wird immer breiter. Als großer Fluss mündet er am Ende ins weite Meer.",
          q: "Wo beginnt der Bach?", a: ["Hoch in den Bergen.", "Tief im Meer.", "In einer Stadt.", "In einem See."] },
        { text: "Der große Baum steht fest im Sturm, weil seine Wurzeln tief in der Erde stecken. Sie halten ihn wie starke Arme. Durch sie trinkt er auch sein Wasser.",
          q: "Warum steht der Baum fest im Sturm?", a: ["Seine Wurzeln halten ihn.", "Seine Blätter sind schwer.", "Er ist aus Stein.", "Der Wind ist schwach."] },
        { text: "Leise rieseln die weißen Schneeflocken vom Himmel. Jede einzelne hat ein anderes Muster, keine gleicht der anderen. Auf der warmen Zunge schmelzen sie sofort weg.",
          q: "Was ist bei jeder Schneeflocke anders?", a: ["Ihr Muster.", "Ihre Farbe.", "Ihr Geräusch.", "Ihr Gewicht."] },
        { text: "Am Morgen geht die Sonne im Osten auf und macht alles hell. Über den Tag wandert sie hoch über den Himmel. Am Abend versinkt sie ganz rot im Westen.",
          q: "Wo geht die Sonne am Morgen auf?", a: ["Im Osten.", "Im Westen.", "Im Norden.", "Genau oben."] },
        { text: "Aus einer kleinen Eichel wächst mit den Jahren eine mächtige Eiche. Das Eichhörnchen vergräbt viele davon. Manche vergisst es — und ein neuer Baum entsteht.",
          q: "Was wächst aus einer Eichel?", a: ["Eine Eiche.", "Ein Pilz.", "Eine Blume.", "Ein Strauch."] },
        { text: "Tief im Berg brodelt heißes, flüssiges Gestein. Manchmal spuckt der Vulkan es als glühende Lava heraus. Dann steigt eine riesige Rauchwolke in den Himmel.",
          q: "Was spuckt der Vulkan heraus?", a: ["Glühende Lava.", "Kaltes Wasser.", "Weißen Schnee.", "Bunte Blumen."] },
        { text: "Wenn es regnet und gleichzeitig die Sonne scheint, entsteht ein Regenbogen. Er spannt sich in sieben Farben über den Himmel. Anfassen kann man ihn aber leider nie.",
          q: "Wann entsteht ein Regenbogen?", a: ["Bei Regen und Sonne zugleich.", "Nur bei Nacht.", "Bei dickem Schnee.", "Bei starkem Wind."] },
      ] },
      { key: "leseAbenteuerB", diff: 2, extends: "leseAbenteuer", items: [
        { text: "Der mutige Ritter reitet zur alten Burg auf dem Berg. Über den tiefen Graben führt nur eine wacklige Zugbrücke. Im dunklen Turm soll ein Schatz versteckt sein.",
          q: "Was führt über den tiefen Graben?", a: ["Eine Zugbrücke.", "Ein langes Seil.", "Ein kleines Boot.", "Eine Leiter."] },
        { text: "Mit einer alten Karte suchen die Kinder den vergrabenen Schatz. Sie zählen die Schritte bis zur großen Eiche. Genau dort, wo das rote X ist, beginnt das Graben.",
          q: "Was zeigt das rote X auf der Karte?", a: ["Wo der Schatz liegt.", "Den Weg nach Hause.", "Ein Piratenschiff.", "Einen Brunnen."] },
        { text: "Am kalten Nordpol baut der Forscher ein Iglu aus festen Schneeblöcken. Drinnen ist es überraschend warm und gemütlich. Draußen tapst neugierig ein Eisbär vorbei.",
          q: "Woraus baut der Forscher das Iglu?", a: ["Aus Schneeblöcken.", "Aus Holz.", "Aus Steinen.", "Aus Eiszapfen."] },
        { text: "Auf der Suche nach dem Tempel führt eine wacklige Seilbrücke über die tiefe Schlucht. Unten rauscht ein wilder Fluss. Mutig setzt die Forscherin Schritt für Schritt.",
          q: "Was rauscht tief unten in der Schlucht?", a: ["Ein wilder Fluss.", "Ein heißer Vulkan.", "Eine große Stadt.", "Ein Zug."] },
        { text: "Mit einem gewaltigen Feuerstrahl startet die Rakete ins All. Die Astronauten drücken sich tief in ihre Sitze. Ihr Ziel ist der rote Planet Mars, weit weg von zu Hause.",
          q: "Wohin fliegt die Rakete?", a: ["Zum Mars.", "Zum Mond.", "Zur Sonne.", "Zu den Sternen."] },
        { text: "Das Piratenschiff wirft vor der einsamen Insel den Anker. Mit einem Ruderboot rudern die Piraten an den Strand. Zwischen den Palmen suchen sie die Schatztruhe.",
          q: "Wie kommen die Piraten an den Strand?", a: ["Mit einem Ruderboot.", "Sie schwimmen.", "Sie fliegen.", "Über eine Brücke."] },
        { text: "Im Museum steht das riesige Skelett eines Dinosauriers. Sein Kopf reicht fast bis zur hohen Decke. Vor Millionen Jahren stapfte er durch die Wälder.",
          q: "Wie groß ist das Dino-Skelett?", a: ["Fast bis zur Decke.", "So klein wie ein Hund.", "So groß wie ein Auto.", "Wie ein Mensch."] },
        { text: "Tagelang wandert die Karawane durch die heiße Wüste. Alle sehnen sich nach Wasser. Endlich taucht am Horizont eine grüne Oase mit kühlen Palmen auf.",
          q: "Wonach sehnen sich alle in der Wüste?", a: ["Nach Wasser.", "Nach Sand.", "Nach Sonne.", "Nach Wärme."] },
        { text: "Mit der Stirnlampe kriecht der Forscher tief in die enge Höhle. An der Decke hängen schlafende Fledermäuse. Plötzlich öffnet sich vor ihm eine riesige Halle.",
          q: "Was hängt an der Höhlendecke?", a: ["Schlafende Fledermäuse.", "Bunte Lampen.", "Lange Seile.", "Große Spinnen."] },
        { text: "Ein wilder Sturm wirft das kleine Segelboot hin und her. Riesige Wellen türmen sich auf. Der Kapitän hält das Steuer fest und segelt mutig gegen den Wind.",
          q: "Was macht der Kapitän im Sturm?", a: ["Er hält das Steuer fest.", "Er springt ins Wasser.", "Er legt sich schlafen.", "Er wirft den Anker."] },
        { text: "Aus dem Flugzeug springt die Fallschirmspringerin in die Tiefe. Erst saust sie schnell nach unten. Dann öffnet sich der Fallschirm mit einem Ruck und sie schwebt sanft.",
          q: "Was passiert, als der Fallschirm aufgeht?", a: ["Sie schwebt sanft.", "Sie fällt schneller.", "Sie fliegt nach oben.", "Sie bleibt stehen."] },
        { text: "Nach dem langen Aufstieg stehen die Wanderer endlich am Gipfel. Unter ihnen liegt ein tiefblauer Bergsee. Ganz klein sehen die Häuser weit unten im Tal aus.",
          q: "Wie sehen die Häuser vom Gipfel aus?", a: ["Ganz klein.", "Riesengroß.", "Bunt bemalt.", "Ganz nah."] },
      ] },
    ],
  },
};

// How many items a language holds — the length of its box digit string (§14.5).
export function itemCount(lang = "de") {
  return CONTENT[lang].packs.reduce((n, p) => n + p.items.length, 0);
}
